### PR TITLE
Added readme

### PR DESCRIPTION
**Pull request by stevenvachon**
~~This will need a connected [greenkeeper](https://greenkeeper.io) account.~~

### CODE REVIEW

**Comment by domenic** [comment]
It's @Sebmaster's call, but please no badges, I hate those things...

**Comment by Sebmaster** [comment]
Yeah, definitely no to the greenkeeper stuff, not planning to use it I think. I'm not so sure about the others.

**Comment by stevenvachon** [comment]
Greenkeeper will tell you if/when a dependency (punycode) gets a major update and whether any tests break. You can patch quicker.

**Comment by stevenvachon** [comment]
...

**Comment by TimothyGu** [comment]
@stevenvachon Can you please remove the badges per request?

For Greenkeeper I've used it before but found it to be annoying as well. I also think it's unlikely for Punycode to get any major updates in the future.

**Pull request merged**
