### PR TITLE
Linting, upgrades, and cleanups

### PR DESCRIPTION
**Pull request by domenic**
On top of #7.

### CODE REVIEW

**Comment by domenic** [comment]
Hmm, the linting seems to have increased the number of failing tests from 488 to 504... maybe that bugfix wasn't so great after all. Investigating.

**Comment by domenic** [comment]
Well, yeah, reverting the bugfix by making it compare the processing function to PROCESSING_OPTIONS values decreases the failing tests back to 504... not sure what to do there.

**Comment by Sebmaster** [comment]
Did node v4 already support arrow functions? Might be a major?

**Comment by domenic** [comment]
Node v4 already supports arrow functions, yeah :) http://node.green/

**Comment by Sebmaster** [comment]
Let's get travis in here while we're at it?

**Comment by domenic** [comment]
Sure, although only you can flip the switch. Should we just not run tests, given the 500 failing ones?

**Comment by Sebmaster** [comment]
Yeah, that's alright with me. Can we get the linting and some basic syntax verification in there (by just running the `index.js` with node)?

**Comment by domenic** [comment]
Sure that makes sense.

**Pull request merged**
